<?php
function checkEmail($e, $secretKey){
	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	$ch = curl_init();
	curl_setopt($ch, CURLOPT_URL, 'https://api.neverbounce.com/v4/single/check?key='.$secretKey.'&email='.$e);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
	$result = curl_exec($ch);
	$resultdecode = json_decode($result, true);
	if($resultdecode['result'] === 'valid') file_put_contents('valid.txt', $e.PHP_EOL, FILE_APPEND) . print "$e - Valid Email".PHP_EOL;
	else print "$e - NOT Valid Email".PHP_EOL;
	if (curl_errno($ch)) {
	    echo 'Error:' . curl_error($ch);
	}
	curl_close($ch);
}
/*API Authentication*/
$secretKey = "";
$myfile = file_get_contents('email.txt');
$explode = explode(PHP_EOL, $myfile);
foreach($explode as $e) checkEmail($e, $secretKey);